# Generated by Django 5.0.13 on 2025-08-25 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0017_alter_bin_bin_height_alter_bin_current_level'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='collector_pickups',
            field=models.ManyToManyField(to='apis.pickup'),
        ),
    ]
