# Generated by Django 5.0.7 on 2024-12-21 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_pickup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pickup',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='pickup',
            name='bin',
        ),
        migrations.AddField(
            model_name='bin',
            name='bin_height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bin',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bin',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bin',
            name='pickup',
            field=models.ManyToManyField(to='apis.pickup'),
        ),
        migrations.AddField(
            model_name='pickup',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pickup',
            name='cleared',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pickup',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
