# Generated by Django 5.0.7 on 2024-12-21 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_alter_pickup_options_remove_pickup_bin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bin',
            old_name='pickup',
            new_name='pickups',
        ),
    ]
