# Generated by Django 5.0.7 on 2024-12-21 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_rename_pickup_bin_pickups'),
    ]

    operations = [
        migrations.AddField(
            model_name='bin',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
