# Generated by Django 5.0.7 on 2024-12-21 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_bin_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bin',
            name='pickups',
            field=models.ManyToManyField(blank=True, null=True, to='apis.pickup'),
        ),
    ]
