# Generated by Django 5.0.7 on 2025-01-06 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_alter_bin_pickups'),
    ]

    operations = [
        migrations.AddField(
            model_name='bin',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bin',
            name='serial_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
