# Generated by Django 5.0.7 on 2025-01-20 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0007_bin_color_alter_bin_serial_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bin',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bin',
            name='bin_height',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='bin',
            name='pickups',
            field=models.ManyToManyField(blank=True, related_name='bin', to='apis.pickup'),
        ),
        migrations.AlterField(
            model_name='bin',
            name='serial_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
