# Generated by Django 5.0.7 on 2025-01-13 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0008_bin_owner_alter_bin_pickups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bin',
            name='pickups',
            field=models.ManyToManyField(blank=True, related_name='bin', to='apis.pickup'),
        ),
    ]
