# Generated by Django 5.0.7 on 2025-02-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0008_bin_owner_alter_bin_bin_height_alter_bin_pickups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bin',
            name='current_level',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='pickup',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
