# Generated by Django 5.0.7 on 2025-02-03 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0009_pickup_updated_at_alter_bin_current_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AlterModelOptions(
            name='bin',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='bin',
            name='transactions',
            field=models.ManyToManyField(blank=True, related_name='bin', to='apis.transaction'),
        ),
    ]
