# Generated by Django 5.0.7 on 2025-02-03 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0010_transaction_alter_bin_options_bin_transactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickup',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
    ]
