# Generated by Django 5.0.7 on 2025-01-20 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0010_alter_bin_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bin',
            name='bin_height',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='bin',
            name='serial_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
