# Generated by Django 5.0.13 on 2025-03-19 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0012_remove_bin_transactions_transaction_cleared_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='pickups',
            field=models.ManyToManyField(blank=True, related_name='transaction', to='apis.pickup'),
        ),
    ]
