# Generated by Django 5.0.13 on 2025-03-29 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0013_transaction_pickups'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
