# Generated by Django 5.0.13 on 2025-03-31 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0014_transaction_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bin',
            name='serial_number',
            field=models.CharField(max_length=50),
        ),
    ]
