# Generated by Django 5.0.13 on 2025-05-14 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0015_alter_bin_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bin',
            name='current_weight',
            field=models.FloatField(default=0.0),
        ),
    ]
