# Generated by Django 5.0.13 on 2025-08-25 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0016_alter_bin_current_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bin',
            name='bin_height',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='bin',
            name='current_level',
            field=models.IntegerField(default=50),
        ),
    ]
