# Generated by Django 5.0.13 on 2025-08-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0017_alter_bin_bin_height_alter_bin_current_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
