# Generated by Django 5.0.13 on 2025-08-27 15:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0018_transaction_payment_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='serial_number',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
