# Generated by Django 5.0.13 on 2025-08-27 16:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0019_alter_transaction_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='serial_number',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
