# Generated by Django 5.0.13 on 2025-08-31 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0020_alter_transaction_serial_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pickup',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-id']},
        ),
    ]
