name: Deploy Django Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build --build-arg SECRET_KEY="${{ secrets.SECRET_KEY }}" -t onismond/autobin:latest .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push Docker Image to Docker Hub
        run: docker push onismond/autobin:latest

      - name: Log out of Docker Hub
        run: docker logout

      - name: SSH into EC2 and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/autobin/AutoBin-backend
            git pull origin main
            sudo docker rmi $(sudo docker images onismond/autobin -q) || true
            sudo docker pull onismond/autobin:latest
            sudo docker-compose down
            sudo docker-compose up -d